// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: rag_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoreKeeperRAG_SearchRules_FullMethodName = "/lorekeeper.LoreKeeperRAG/SearchRules"
)

// LoreKeeperRAGClient is the client API for LoreKeeperRAG service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoreKeeperRAGClient interface {
	SearchRules(ctx context.Context, in *RuleQuery, opts ...grpc.CallOption) (*RuleContext, error)
}

type loreKeeperRAGClient struct {
	cc grpc.ClientConnInterface
}

func NewLoreKeeperRAGClient(cc grpc.ClientConnInterface) LoreKeeperRAGClient {
	return &loreKeeperRAGClient{cc}
}

func (c *loreKeeperRAGClient) SearchRules(ctx context.Context, in *RuleQuery, opts ...grpc.CallOption) (*RuleContext, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleContext)
	err := c.cc.Invoke(ctx, LoreKeeperRAG_SearchRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoreKeeperRAGServer is the server API for LoreKeeperRAG service.
// All implementations must embed UnimplementedLoreKeeperRAGServer
// for forward compatibility.
type LoreKeeperRAGServer interface {
	SearchRules(context.Context, *RuleQuery) (*RuleContext, error)
	mustEmbedUnimplementedLoreKeeperRAGServer()
}

// UnimplementedLoreKeeperRAGServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoreKeeperRAGServer struct{}

func (UnimplementedLoreKeeperRAGServer) SearchRules(context.Context, *RuleQuery) (*RuleContext, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchRules not implemented")
}
func (UnimplementedLoreKeeperRAGServer) mustEmbedUnimplementedLoreKeeperRAGServer() {}
func (UnimplementedLoreKeeperRAGServer) testEmbeddedByValue()                       {}

// UnsafeLoreKeeperRAGServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoreKeeperRAGServer will
// result in compilation errors.
type UnsafeLoreKeeperRAGServer interface {
	mustEmbedUnimplementedLoreKeeperRAGServer()
}

func RegisterLoreKeeperRAGServer(s grpc.ServiceRegistrar, srv LoreKeeperRAGServer) {
	// If the following call panics, it indicates UnimplementedLoreKeeperRAGServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoreKeeperRAG_ServiceDesc, srv)
}

func _LoreKeeperRAG_SearchRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoreKeeperRAGServer).SearchRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoreKeeperRAG_SearchRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoreKeeperRAGServer).SearchRules(ctx, req.(*RuleQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// LoreKeeperRAG_ServiceDesc is the grpc.ServiceDesc for LoreKeeperRAG service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoreKeeperRAG_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lorekeeper.LoreKeeperRAG",
	HandlerType: (*LoreKeeperRAGServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchRules",
			Handler:    _LoreKeeperRAG_SearchRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rag_service.proto",
}
