// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rag_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	CampaignId    string                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleQuery) Reset() {
	*x = RuleQuery{}
	mi := &file_rag_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleQuery) ProtoMessage() {}

func (x *RuleQuery) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleQuery.ProtoReflect.Descriptor instead.
func (*RuleQuery) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{0}
}

func (x *RuleQuery) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *RuleQuery) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type RuleContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Rules          []string               `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	Source         string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	RelevanceScore float32                `protobuf:"fixed32,3,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuleContext) Reset() {
	*x = RuleContext{}
	mi := &file_rag_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleContext) ProtoMessage() {}

func (x *RuleContext) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleContext.ProtoReflect.Descriptor instead.
func (*RuleContext) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{1}
}

func (x *RuleContext) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *RuleContext) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RuleContext) GetRelevanceScore() float32 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

var File_rag_service_proto protoreflect.FileDescriptor

const file_rag_service_proto_rawDesc = "" +
	"\n" +
	"\x11rag_service.proto\x12\n" +
	"lorekeeper\"H\n" +
	"\tRuleQuery\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\tR\n" +
	"campaignId\"d\n" +
	"\vRuleContext\x12\x14\n" +
	"\x05rules\x18\x01 \x03(\tR\x05rules\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12'\n" +
	"\x0frelevance_score\x18\x03 \x01(\x02R\x0erelevanceScore2N\n" +
	"\rLoreKeeperRAG\x12=\n" +
	"\vSearchRules\x12\x15.lorekeeper.RuleQuery\x1a\x17.lorekeeper.RuleContextB\x06Z\x04./pbb\x06proto3"

var (
	file_rag_service_proto_rawDescOnce sync.Once
	file_rag_service_proto_rawDescData []byte
)

func file_rag_service_proto_rawDescGZIP() []byte {
	file_rag_service_proto_rawDescOnce.Do(func() {
		file_rag_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_service_proto_rawDesc), len(file_rag_service_proto_rawDesc)))
	})
	return file_rag_service_proto_rawDescData
}

var file_rag_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rag_service_proto_goTypes = []any{
	(*RuleQuery)(nil),   // 0: lorekeeper.RuleQuery
	(*RuleContext)(nil), // 1: lorekeeper.RuleContext
}
var file_rag_service_proto_depIdxs = []int32{
	0, // 0: lorekeeper.LoreKeeperRAG.SearchRules:input_type -> lorekeeper.RuleQuery
	1, // 1: lorekeeper.LoreKeeperRAG.SearchRules:output_type -> lorekeeper.RuleContext
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rag_service_proto_init() }
func file_rag_service_proto_init() {
	if File_rag_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_service_proto_rawDesc), len(file_rag_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_service_proto_goTypes,
		DependencyIndexes: file_rag_service_proto_depIdxs,
		MessageInfos:      file_rag_service_proto_msgTypes,
	}.Build()
	File_rag_service_proto = out.File
	file_rag_service_proto_goTypes = nil
	file_rag_service_proto_depIdxs = nil
}
